---
title: "File input/output"
author: "Wesley G"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(gapminder)
```

```{r}
(gap_asia_2007 <- gapminder %>% filter(year == 2007, continent == "Asia"))
```

```{r}
# write_csv(gap_asia_2007, here::here("data","s008_data", "exported_file.csv"))
read_csv(here::here("data", "s008_data", "exported_file.csv"))
```

```{r}
url <- "http://gattonweb.uky.edu/sheather/book/docs/datasets/magazines.csv"
read_csv(url)
#Creates files as we goo!!!!1!!!

#dir.create(here::here("data", "s008_data"), recursive = TRUE)
```


```{r}
library(haven)
(clevel <- haven::read_spss(here::here("data", "s008_data", "clevel.sav")))


clevel_cleaned <-
  clevel %>% 
  mutate(language = as_factor(language),
         gender = as_factor(gender),
         isClevel = factor(isClevel, 
                           levels = c(0, 1), 
                           labels = c("No", "Yes"))
  ) %>% 
  print()

write_csv(clevel_cleaned, here::here("data", "s008_data", "clevel_cleaned.csv"))

library(ggthemes)

clevel_plot <-
  clevel_cleaned %>% 
  mutate(isClevel = recode(isClevel, 
                           No = "Below C-level", 
                           Yes = "C-level"),
         gender = recode(gender,
                         Female = "Women",
                         Male = "Men")) %>% 
  ggplot(aes(paste(isClevel, gender, sep = "\n"), Extraversion, color = gender)) +
  geom_boxplot() +
  geom_jitter(height = .2) +
  scale_color_manual(values = c("#1b9e77", "#7570b3")) +
  ggtitle("Extraversion Stan Scores") +
  scale_y_continuous(breaks = 1:9) 
```


```{r}
dir.create(here::here("output", "figures"), recursive = TRUE)
ggsave(here::here("output", "figures", "clevel_extraversion.svg"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.eps"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.pdf"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.tiff"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.png"), clevel_plot)
```

```{r}

```

